import Head from 'next/head';

import { FC, PropsWithChildren } from 'react';
import { IconLinkedin } from '../icons';
import { Navbar } from '../navbar/Navbar';

import { Footer, Header, SectionRigth, SectionLefth } from './layoutStyled';

interface Props {
	title?: string;
}

export const Layout: FC<PropsWithChildren<Props>> = ({ children, title }) => {
	return (
		<>
			<Head>
				<title>{title || 'Portafolio'}</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/icons/program (2).png' />
			</Head>
			<Header>
				<Navbar />
			</Header>
			<div>{children}</div>
			<Footer>
				<div>
					<SectionLefth>
						<p>pagina creada por eduardo padrino</p>
					</SectionLefth>
					<SectionRigth className='b'>
						<section>
							<IconLinkedin width='100%' height='100%' />
						</section>
					</SectionRigth>
				</div>
			</Footer>
		</>
	);
};
